import React, { createContext, useContext, useEffect, useState } from 'react';

// ── Supported languages ────────────────────────────────────────────────────
export const LANGUAGES = [
  { code: 'English',     label: 'English',      flag: '🇬🇧', locale: ['en'] },
  { code: 'हिंदी',       label: 'हिंदी',        flag: '🇮🇳', locale: ['hi'] },
  { code: 'বাংলা',       label: 'বাংলা',        flag: '🔵', locale: ['bn'] },
  { code: 'ਪੰਜਾਬੀ',     label: 'ਪੰਜਾਬੀ',      flag: '🟠', locale: ['pa'] },
  { code: 'தமிழ்',      label: 'தமிழ்',       flag: '🔴', locale: ['ta'] },
  { code: 'తెలుగు',     label: 'తెలుగు',      flag: '🟡', locale: ['te'] },
  { code: 'मराठी',       label: 'मराठी',        flag: '🟣', locale: ['mr'] },
  { code: 'ગુજરાતી',    label: 'ગુજરાતી',     flag: '🟢', locale: ['gu'] },
  { code: 'ಕನ್ನಡ',      label: 'ಕನ್ನಡ',       flag: '🟤', locale: ['kn'] },
  { code: 'മലയാളം',     label: 'മലയാളം',      flag: '🟦', locale: ['ml'] },
  { code: 'ଓଡ଼ିଆ',      label: 'ଓଡ଼ିଆ',        flag: '🔶', locale: ['or'] },
  { code: 'অসমীয়া',    label: 'অসমীয়া',      flag: '🔷', locale: ['as'] },
  { code: 'اردو',        label: 'اردو',          flag: '🌙', locale: ['ur'] },
  { code: 'नेपाली',      label: 'नेपाली',        flag: '⛰️', locale: ['ne'] },
  { code: 'মৈতৈলোন্',   label: 'মৈতৈলোন্',    flag: '🌺', locale: ['mni'] },
  { code: 'संस्कृत',    label: 'संस्कृत',      flag: '📿', locale: ['sa'] },
  { code: 'मैथिली',      label: 'मैथिली',        flag: '🌼', locale: ['mai'] },
  { code: 'डोगरी',       label: 'डोगरी',         flag: '🏔️', locale: ['doi'] },
  { code: 'कोंकणी',     label: 'कोंकणी',       flag: '🌴', locale: ['kok'] },
  { code: 'सिन्धी',     label: 'सिन्धी',       flag: '🌊', locale: ['sd'] },
  { code: 'बड़ो',        label: 'बड़ो',           flag: '🌿', locale: ['brx'] },
  { code: 'ᱥᱟᱱᱛᱟᱲᱤ',  label: 'ᱥᱟᱱᱛᱟᱲᱤ',    flag: '🌾', locale: ['sat'] },
  { code: 'कश्मीरी',    label: 'कश्मीरी',      flag: '❄️', locale: ['ks'] },
];

// ── Translation tables ─────────────────────────────────────────────────────
const T = {
  English: {
    dashboard: '🏠 Dashboard',     myChild: '👶 My Child',
    vaccines:  '💉 Vaccines',      growth:  '📈 Growth',
    dietPlan:  '🥗 Diet Plan',     schemes: '🏛️ Schemes',
    reports:   '📋 Reports',       notifications: '🔔 Notifications',
    settings:  '⚙️ Settings',
    welcome: 'Welcome back',       addChild: 'Add Child',
    bookVaccine: 'Book Vaccine',   logGrowth: 'Log Growth',
    downloadReport: 'Download Report', viewProfile: 'View Profile',
    healthScore: 'Health Score',   saveAll: '💾 Save All Changes',
    langTitle: 'Language Preference', langSub: 'Choose your preferred language',
    profileTitle: 'Parent / Guardian Profile', profileSub: 'Your registered account information',
    childInfoTitle: 'Child Information', childInfoSub: "Registered child's health profile",
    notifTitle: 'Notification Settings', notifSub: 'Manage what alerts you receive',
    secTitle: 'Security', secSub: 'Change your account password',
    downloadAll: '📥 Download All Reports',
    bookAppt: '📅 Book Appointment', vaccineCard: '💳 Vaccine Card',
    setReminder: '🔔 Set Reminder',  bookNow: '📅 Book Now',
    checkStatus: 'Check Status →',   checkEligibility: 'Check Eligibility →',
    nearbyHospitals: '🏥 Nearby Hospitals', searchLocation: 'Search location…',
    recordGrowth: '📏 Record Growth', weightKg: 'Weight (kg)', heightCm: 'Height (cm)',
    save: 'Save', cancel: 'Cancel', markDone: 'Mark Done',
    dietPlanFor: 'Diet Plan for', ageMonths: 'months old',
    // Auth
    loginTitle: 'Welcome back', loginSubtitle: 'Sign in to your portal to continue',
    loginBtn: 'Sign In', registerBtn: 'Create Account', register: 'Register',
    email: 'Email / Phone', phone: 'Phone Number', password: 'Password',
    enterPassword: 'Enter your password', fullName: 'Full Name',
    selectRole: 'Select your role', forgotPassword: 'Forgot password?',
    keepSignedIn: 'Keep me signed in', noAccount: 'New to Sishu Arogaya?',
    alreadyAccount: 'Already have an account?', login: 'Login',
    registerTitle: 'Create your account',
    otpVerify: 'Verify OTP', otpSubtitle: 'Enter the OTP sent to your registered email',
    otpLabel: 'One-Time Password', otpRequired: 'OTP verification is required before continuing.',
    verifyLogin: 'Verify & Login', backToLogin: 'Back to Login', redirecting: 'Redirecting…',
    // Common
    logout: 'Logout', home: 'Home', back: 'Back', next: 'Next', loading: 'Loading…',
    search: 'Search', filter: 'Filter', view: 'View', edit: 'Edit', delete: 'Delete',
    add: 'Add', close: 'Close', yes: 'Yes', no: 'No', ok: 'OK', confirm: 'Confirm',
    update: 'Update', refresh: 'Refresh', download: 'Download', upload: 'Upload',
    // ASHA
    myChildren: 'My Children', logVisit: 'Log Visit', visitHistory: 'Visit History',
    growthRecords: 'Growth Records', vaccinationTracker: 'Vaccination Tracker',
    malnutritionReport: 'Malnutrition Report', assignedChildren: 'Assigned Children',
    totalChildren: 'Total Children', healthyChildren: 'Healthy', severeChildren: 'Severe',
    pendingVisits: 'Pending Visits', overdueVaccines: 'Overdue Vaccines',
    recentVisits: 'Recent Visits', lastVisit: 'Last Visit', nextVisit: 'Next Visit',
    visitType: 'Visit Type', visitNotes: 'Notes', visitOutcome: 'Outcome',
    logNewVisit: 'Log New Visit', selectChild: 'Select Child',
    generateReport: 'Generate Report', selectOption: 'Select…',
    // Status
    healthy: 'Healthy', moderate: 'Moderate', severe: 'Severe', normal: 'Normal',
    overdue: 'Overdue', completed: 'Completed', pending: 'Pending', upcoming: 'Upcoming',
    noData: 'No data available', noRecords: 'No records found',
    // Medical
    weight: 'Weight', height: 'Height', vaccination: 'Vaccination',
    malnutrition: 'Malnutrition', nutrition: 'Nutrition', status: 'Status',
    childName: 'Child Name', dateOfBirth: 'Date of Birth',
    gender: 'Gender', bloodGroup: 'Blood Group', address: 'Address',
    male: 'Male', female: 'Female', other: 'Other',
    // ASHA extra
    visitsThisMonth: 'Visits This Month', viewAll: 'View All',
    severeCases: 'Severe Cases', moderateCases: 'Moderate Cases',
    ashaPortal: 'ASHA Worker Portal', blockHealthSummary: 'Block Health Summary',
    noOverdueVaccines: '✅ No overdue vaccines!', recentVisitLog: 'Recent Visit Log',
    fullHistory: 'Full History', vaccineCoverage: 'Block Vaccine Coverage',
    coverageLegend: 'Coverage Legend', upcomingCamps: 'Upcoming Vaccination Camps',
    markGiven: 'Mark Given', nextVaccine: 'Next Vaccine',
    action: 'Action', age: 'Age', date: 'Date', type: 'Type',
    noChildrenAssigned: 'No children assigned yet',
    searchByName: 'Search by child name…',
    phcReferralNeeded: 'PHC referral needed', allUpToDate: 'All up to date',
    followUpNeeded: 'Follow-up needed', noVisitsYet: 'No visits logged yet',
    growthEntry: 'Log Growth Entry', malnutritionCases: 'Malnutrition Cases',
    urgentAction: 'Immediate Action Required', logVisitPage: 'Log Home Visit',
    childrenAssignedLabel: 'children assigned',
    // Admin extra
    adminPortal: 'Admin Portal', userManagement: 'User Management',
    ashaWorkers: 'ASHA Workers', districtHeatmap: 'District Heatmap',
    analyticsReports: 'Analytics & Reports', childrenRegistry: 'Children Registry',
    malnutritionCasesAdmin: 'Malnutrition Cases', vaccinationData: 'Vaccination Data',
    governmentSchemes: 'Government Schemes', blockwiseReports: 'Blockwise Reports',
    notificationsPanel: 'Notifications Panel', healthCentreDirectory: 'Health Centre Directory',
    settingsConfig: 'Settings & Configuration', auditLogs: 'Audit Logs',
    totalUsers: 'Total Users', activeUsers: 'Active Users', pendingApprovals: 'Pending Approvals',
    totalReports: 'Total Reports', exportData: 'Export Data', importData: 'Import Data',
    approve: 'Approve', reject: 'Reject', suspend: 'Suspend', activate: 'Activate',
    role: 'Role', lastLogin: 'Last Login', createdAt: 'Created At', actions: 'Actions',
    name: 'Name', email2: 'Email', phone2: 'Phone', district: 'District', block: 'Block',
    village: 'Village', state: 'State', country: 'Country',
  },
  हिंदी: {
    dashboard: '🏠 डैशबोर्ड',     myChild: '👶 मेरा बच्चा',
    vaccines:  '💉 टीकाकरण',      growth:  '📈 विकास',
    dietPlan:  '🥗 आहार योजना',   schemes: '🏛️ सरकारी योजनाएं',
    reports:   '📋 रिपोर्ट',      notifications: '🔔 सूचनाएं',
    settings:  '⚙️ सेटिंग्स',
    welcome: 'वापस स्वागत है',     addChild: 'बच्चा जोड़ें',
    bookVaccine: 'टीका बुक करें',  logGrowth: 'विकास दर्ज करें',
    downloadReport: 'रिपोर्ट डाउनलोड करें', viewProfile: 'प्रोफाइल देखें',
    healthScore: 'स्वास्थ्य स्कोर', saveAll: '💾 सभी बदलाव सहेजें',
    langTitle: 'भाषा वरीयता',     langSub: 'अपनी पसंदीदा भाषा चुनें',
    profileTitle: 'माता-पिता / अभिभावक प्रोफाइल', profileSub: 'आपकी पंजीकृत खाता जानकारी',
    childInfoTitle: 'बच्चे की जानकारी', childInfoSub: 'पंजीकृत बच्चे का स्वास्थ्य प्रोफाइल',
    notifTitle: 'सूचना सेटिंग्स', notifSub: 'प्रबंधित करें कि आपको कौन से अलर्ट मिलते हैं',
    secTitle: 'सुरक्षा', secSub: 'अपना खाता पासवर्ड बदलें',
    downloadAll: '📥 सभी रिपोर्ट डाउनलोड करें',
    bookAppt: '📅 अपॉइंटमेंट बुक करें', vaccineCard: '💳 वैक्सीन कार्ड',
    setReminder: '🔔 अनुस्मारक सेट करें', bookNow: '📅 अभी बुक करें',
    checkStatus: 'स्थिति जांचें →', checkEligibility: 'पात्रता जांचें →',
    nearbyHospitals: '🏥 नजदीकी अस्पताल', searchLocation: 'स्थान खोजें…',
    recordGrowth: '📏 विकास दर्ज करें', weightKg: 'वजन (किग्रा)', heightCm: 'ऊंचाई (सेमी)',
    save: 'सहेजें', cancel: 'रद्द करें', markDone: 'पूर्ण करें',
    dietPlanFor: 'आहार योजना', ageMonths: 'महीने का',
    loginTitle: 'वापस स्वागत है', loginSubtitle: 'जारी रखने के लिए साइन इन करें',
    loginBtn: 'साइन इन', registerBtn: 'खाता बनाएं', register: 'पंजीकरण',
    email: 'ईमेल / फ़ोन', phone: 'फ़ोन नंबर', password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड डालें', fullName: 'पूरा नाम',
    selectRole: 'अपनी भूमिका चुनें', forgotPassword: 'पासवर्ड भूल गए?',
    keepSignedIn: 'मुझे साइन इन रखें', noAccount: 'Sishu Arogaya में नए हैं?',
    alreadyAccount: 'पहले से खाता है?', login: 'लॉगिन',
    registerTitle: 'अपना खाता बनाएं',
    otpVerify: 'OTP सत्यापित करें', otpSubtitle: 'अपने ईमेल पर भेजे गए OTP को दर्ज करें',
    otpLabel: 'वन-टाइम पासवर्ड', otpRequired: 'आगे जाने से पहले OTP सत्यापन आवश्यक है।',
    verifyLogin: 'सत्यापित करें और लॉगिन', backToLogin: 'लॉगिन पर वापस', redirecting: 'रीडायरेक्ट हो रहा है…',
    logout: 'लॉगआउट', home: 'होम', back: 'वापस', next: 'अगला', loading: 'लोड हो रहा है…',
    search: 'खोजें', filter: 'फ़िल्टर', view: 'देखें', edit: 'संपादित करें', delete: 'हटाएं',
    add: 'जोड़ें', close: 'बंद करें', yes: 'हाँ', no: 'नहीं', ok: 'ठीक', confirm: 'पुष्टि करें',
    update: 'अपडेट', refresh: 'रिफ्रेश', download: 'डाउनलोड', upload: 'अपलोड',
    myChildren: 'मेरे बच्चे', logVisit: 'विजिट दर्ज करें', visitHistory: 'विजिट इतिहास',
    growthRecords: 'विकास रिकॉर्ड', vaccinationTracker: 'टीकाकरण ट्रैकर',
    malnutritionReport: 'कुपोषण रिपोर्ट', assignedChildren: 'सौंपे गए बच्चे',
    totalChildren: 'कुल बच्चे', healthyChildren: 'स्वस्थ', severeChildren: 'गंभीर',
    pendingVisits: 'लंबित विजिट', overdueVaccines: 'लंबित टीके',
    recentVisits: 'हालिया विजिट', lastVisit: 'अंतिम विजिट', nextVisit: 'अगली विजिट',
    visitType: 'विजिट प्रकार', visitNotes: 'नोट्स', visitOutcome: 'परिणाम',
    logNewVisit: 'नई विजिट दर्ज करें', selectChild: 'बच्चा चुनें',
    generateReport: 'रिपोर्ट बनाएं', selectOption: 'चुनें…',
    healthy: 'स्वस्थ', moderate: 'मध्यम', severe: 'गंभीर', normal: 'सामान्य',
    overdue: 'समयसीमा पार', completed: 'पूर्ण', pending: 'लंबित', upcoming: 'आगामी',
    noData: 'कोई डेटा उपलब्ध नहीं', noRecords: 'कोई रिकॉर्ड नहीं',
    weight: 'वजन', height: 'ऊंचाई', vaccination: 'टीकाकरण',
    malnutrition: 'कुपोषण', nutrition: 'पोषण', status: 'स्थिति',
    childName: 'बच्चे का नाम', dateOfBirth: 'जन्म तिथि',
    gender: 'लिंग', bloodGroup: 'रक्त समूह', address: 'पता',
    male: 'पुरुष', female: 'महिला', other: 'अन्य',
    // ASHA extra
    visitsThisMonth: 'इस माह की विज़िट', viewAll: 'सभी देखें',
    severeCases: 'गंभीर मामले', moderateCases: 'मध्यम मामले',
    ashaPortal: 'आशा कार्यकर्ता पोर्टल', blockHealthSummary: 'ब्लॉक स्वास्थ्य सारांश',
    noOverdueVaccines: '✅ कोई बकाया टीका नहीं!', recentVisitLog: 'हालिया विज़िट लॉग',
    fullHistory: 'पूरा इतिहास', vaccineCoverage: 'ब्लॉक वैक्सीन कवरेज',
    coverageLegend: 'कवरेज लेजेंड', upcomingCamps: 'आगामी टीकाकरण शिविर',
    markGiven: 'दिया गया चिह्नित करें', nextVaccine: 'अगला टीका',
    action: 'कार्रवाई', age: 'आयु', date: 'दिनांक', type: 'प्रकार',
    noChildrenAssigned: 'अभी तक कोई बच्चा नहीं सौंपा गया',
    searchByName: 'बच्चे का नाम खोजें…',
    phcReferralNeeded: 'PHC रेफरल आवश्यक', allUpToDate: 'सब अद्यतन हैं',
    followUpNeeded: 'फॉलो-अप आवश्यक', noVisitsYet: 'अभी तक कोई विज़िट नहीं',
    growthEntry: 'विकास प्रविष्टि दर्ज करें', malnutritionCases: 'कुपोषण मामले',
    urgentAction: 'तत्काल कार्रवाई आवश्यक', logVisitPage: 'घर विज़िट दर्ज करें',
    childrenAssignedLabel: 'बच्चे सौंपे गए',
    // Admin extra
    adminPortal: 'एडमिन पोर्टल', userManagement: 'उपयोगकर्ता प्रबंधन',
    ashaWorkers: 'आशा कार्यकर्ता', districtHeatmap: 'जिला हीटमैप',
    analyticsReports: 'एनालिटिक्स और रिपोर्ट', childrenRegistry: 'बच्चों की रजिस्ट्री',
    malnutritionCasesAdmin: 'कुपोषण मामले', vaccinationData: 'टीकाकरण डेटा',
    governmentSchemes: 'सरकारी योजनाएं', blockwiseReports: 'ब्लॉकवार रिपोर्ट',
    notificationsPanel: 'सूचना पैनल', healthCentreDirectory: 'स्वास्थ्य केंद्र निर्देशिका',
    settingsConfig: 'सेटिंग्स और कॉन्फ़िगरेशन', auditLogs: 'ऑडिट लॉग',
    totalUsers: 'कुल उपयोगकर्ता', activeUsers: 'सक्रिय उपयोगकर्ता', pendingApprovals: 'लंबित अनुमोदन',
    totalReports: 'कुल रिपोर्ट', exportData: 'डेटा निर्यात', importData: 'डेटा आयात',
    approve: 'अनुमोदन', reject: 'अस्वीकार', suspend: 'निलंबित', activate: 'सक्रिय',
    role: 'भूमिका', lastLogin: 'अंतिम लॉगिन', createdAt: 'बनाई गई', actions: 'कार्रवाइयाँ',
    name: 'नाम', email2: 'ईमेल', phone2: 'फ़ोन', district: 'जिला', block: 'ब्लॉक',
    village: 'गाँव', state: 'राज्य', country: 'देश',
  },
  বাংলা: {
    dashboard: '🏠 ড্যাশবোর্ড',  myChild: '👶 আমার শিশু',
    vaccines:  '💉 টিকা',         growth:  '📈 বৃদ্ধি',
    dietPlan:  '🥗 খাদ্য পরিকল্পনা', schemes: '🏛️ সরকারি প্রকল্প',
    reports:   '📋 রিপোর্ট',     notifications: '🔔 বিজ্ঞপ্তি',
    settings:  '⚙️ সেটিংস',
    welcome: 'ফিরে স্বাগতম',     addChild: 'শিশু যোগ করুন',
    bookVaccine: 'টিকা বুক করুন', logGrowth: 'বৃদ্ধি লগ করুন',
    downloadReport: 'রিপোর্ট ডাউনলোড করুন', viewProfile: 'প্রোফাইল দেখুন',
    healthScore: 'স্বাস্থ্য স্কোর', saveAll: '💾 সব পরিবর্তন সংরক্ষণ করুন',
    langTitle: 'ভাষা পছন্দ',     langSub: 'আপনার পছন্দের ভাষা বেছে নিন',
    profileTitle: 'অভিভাবক প্রোফাইল', profileSub: 'আপনার নিবন্ধিত অ্যাকাউন্টের তথ্য',
    childInfoTitle: 'শিশুর তথ্য', childInfoSub: 'নিবন্ধিত শিশুর স্বাস্থ্য প্রোফাইল',
    notifTitle: 'বিজ্ঞপ্তি সেটিংস', notifSub: 'কোন সতর্কতা পাবেন তা পরিচালনা করুন',
    secTitle: 'নিরাপত্তা', secSub: 'আপনার অ্যাকাউন্ট পাসওয়ার্ড পরিবর্তন করুন',
    downloadAll: '📥 সব রিপোর্ট ডাউনলোড করুন',
    bookAppt: '📅 অ্যাপয়েন্টমেন্ট বুক করুন', vaccineCard: '💳 ভ্যাকসিন কার্ড',
    setReminder: '🔔 রিমাইন্ডার সেট করুন', bookNow: '📅 এখনই বুক করুন',
    checkStatus: 'স্থিতি পরীক্ষা করুন →', checkEligibility: 'যোগ্যতা পরীক্ষা করুন →',
    nearbyHospitals: '🏥 কাছের হাসপাতাল', searchLocation: 'অবস্থান খুঁজুন…',
    recordGrowth: '📏 বৃদ্ধি রেকর্ড করুন', weightKg: 'ওজন (কেজি)', heightCm: 'উচ্চতা (সেমি)',
    save: 'সংরক্ষণ', cancel: 'বাতিল', markDone: 'সম্পন্ন করুন',
    dietPlanFor: 'খাদ্য পরিকল্পনা', ageMonths: 'মাস বয়সী',
  },
  ਪੰਜਾਬੀ: {
    dashboard: '🏠 ਡੈਸ਼ਬੋਰਡ',     myChild: '👶 ਮੇਰਾ ਬੱਚਾ',
    vaccines:  '💉 ਟੀਕਾਕਰਣ',      growth:  '📈 ਵਿਕਾਸ',
    dietPlan:  '🥗 ਖੁਰਾਕ ਯੋਜਨਾ', schemes: '🏛️ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    reports:   '📋 ਰਿਪੋਰਟ',      notifications: '🔔 ਸੂਚਨਾਵਾਂ',
    settings:  '⚙️ ਸੈਟਿੰਗਾਂ',
    welcome: 'ਵਾਪਸ ਸੁਆਗਤ ਹੈ',    addChild: 'ਬੱਚਾ ਜੋੜੋ',
    bookVaccine: 'ਟੀਕਾ ਬੁੱਕ ਕਰੋ', logGrowth: 'ਵਿਕਾਸ ਦਰਜ ਕਰੋ',
    downloadReport: 'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ', viewProfile: 'ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ',
    healthScore: 'ਸਿਹਤ ਸਕੋਰ',    saveAll: '💾 ਸਾਰੀਆਂ ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ',
    langTitle: 'ਭਾਸ਼ਾ ਤਰਜੀਹ',    langSub: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
    profileTitle: 'ਮਾਤਾ-ਪਿਤਾ ਪ੍ਰੋਫਾਈਲ', profileSub: 'ਤੁਹਾਡੀ ਰਜਿਸਟਰਡ ਖਾਤਾ ਜਾਣਕਾਰੀ',
    childInfoTitle: 'ਬੱਚੇ ਦੀ ਜਾਣਕਾਰੀ', childInfoSub: 'ਰਜਿਸਟਰਡ ਬੱਚੇ ਦਾ ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ',
    notifTitle: 'ਸੂਚਨਾ ਸੈਟਿੰਗਾਂ', notifSub: 'ਅਲਰਟ ਪ੍ਰਬੰਧਿਤ ਕਰੋ',
    secTitle: 'ਸੁਰੱਖਿਆ', secSub: 'ਪਾਸਵਰਡ ਬਦਲੋ',
    downloadAll: '📥 ਸਾਰੀਆਂ ਰਿਪੋਰਟਾਂ ਡਾਊਨਲੋਡ ਕਰੋ',
    bookAppt: '📅 ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ', vaccineCard: '💳 ਵੈਕਸੀਨ ਕਾਰਡ',
    setReminder: '🔔 ਯਾਦ ਦਿਵਾਉਣਾ ਸੈਟ ਕਰੋ', bookNow: '📅 ਹੁਣੇ ਬੁੱਕ ਕਰੋ',
    checkStatus: 'ਸਥਿਤੀ ਜਾਂਚੋ →', checkEligibility: 'ਯੋਗਤਾ ਜਾਂਚੋ →',
    nearbyHospitals: '🏥 ਨੇੜਲੇ ਹਸਪਤਾਲ', searchLocation: 'ਸਥਾਨ ਖੋਜੋ…',
    recordGrowth: '📏 ਵਿਕਾਸ ਦਰਜ ਕਰੋ', weightKg: 'ਭਾਰ (ਕਿਲੋ)', heightCm: 'ਕੱਦ (ਸੈ.ਮੀ.)',
    save: 'ਸੇਵ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ', markDone: 'ਪੂਰਾ ਕਰੋ',
    dietPlanFor: 'ਖੁਰਾਕ ਯੋਜਨਾ', ageMonths: 'ਮਹੀਨੇ ਦੀ ਉਮਰ',
  },
  தமிழ்: {
    dashboard: '🏠 டாஷ்போர்டு',  myChild: '👶 என் குழந்தை',
    vaccines:  '💉 தடுப்பூசி',   growth:  '📈 வளர்ச்சி',
    dietPlan:  '🥗 உணவு திட்டம்', schemes: '🏛️ அரசு திட்டங்கள்',
    reports:   '📋 அறிக்கைகள்',  notifications: '🔔 அறிவிப்புகள்',
    settings:  '⚙️ அமைப்புகள்',
    welcome: 'மீண்டும் வரவேற்கிறோம்', addChild: 'குழந்தை சேர்க்கவும்',
    bookVaccine: 'தடுப்பூசி பதிவு',   logGrowth: 'வளர்ச்சி பதிவு',
    downloadReport: 'அறிக்கை பதிவிறக்கு', viewProfile: 'சுயவிவரம் பார்க்கவும்',
    healthScore: 'சுகாதார மதிப்பெண்',  saveAll: '💾 அனைத்தையும் சேமிக்கவும்',
    langTitle: 'மொழி விருப்பம்',      langSub: 'விருப்பமான மொழியை தேர்ந்தெடுக்கவும்',
    profileTitle: 'பெற்றோர் சுயவிவரம்', profileSub: 'பதிவு செய்யப்பட்ட கணக்கு தகவல்',
    childInfoTitle: 'குழந்தை தகவல்',  childInfoSub: 'பதிவு செய்யப்பட்ட குழந்தையின் சுகாதார சுயவிவரம்',
    notifTitle: 'அறிவிப்பு அமைப்புகள்', notifSub: 'எச்சரிக்கைகளை நிர்வகிக்கவும்',
    secTitle: 'பாதுகாப்பு', secSub: 'கடவுச்சொல் மாற்றவும்',
    downloadAll: '📥 அனைத்து அறிக்கைகளையும் பதிவிறக்கவும்',
    bookAppt: '📅 நேரம் பதிவு', vaccineCard: '💳 தடுப்பூசி அட்டை',
    setReminder: '🔔 நினைவூட்டல் அமை', bookNow: '📅 இப்போது பதிவு',
    checkStatus: 'நிலையை சரிபார்க்கவும் →', checkEligibility: 'தகுதியை சரிபார்க்கவும் →',
    nearbyHospitals: '🏥 அருகிலுள்ள மருத்துவமனைகள்', searchLocation: 'இடம் தேடவும்…',
    recordGrowth: '📏 வளர்ச்சி பதிவு', weightKg: 'எடை (கிகி)', heightCm: 'உயரம் (செமீ)',
    save: 'சேமிக்கவும்', cancel: 'ரத்து', markDone: 'முடிந்தது',
    dietPlanFor: 'உணவு திட்டம்', ageMonths: 'மாத வயது',
  },
  తెలుగు: {
    dashboard: '🏠 డాష్‌బోర్డ్',  myChild: '👶 నా పిల్లవాడు',
    vaccines:  '💉 టీకాలు',       growth:  '📈 పెరుగుదల',
    dietPlan:  '🥗 ఆహార ప్రణాళిక', schemes: '🏛️ ప్రభుత్వ పథకాలు',
    reports:   '📋 నివేదికలు',    notifications: '🔔 నోటిఫికేషన్లు',
    settings:  '⚙️ సెట్టింగులు',
    welcome: 'తిరిగి స్వాగతం',    addChild: 'పిల్లవాడిని జోడించు',
    bookVaccine: 'టీకా బుక్ చేయి', logGrowth: 'పెరుగుదల నమోదు',
    downloadReport: 'నివేదిక డౌన్‌లోడ్', viewProfile: 'ప్రొఫైల్ చూడు',
    healthScore: 'ఆరోగ్య స్కోరు',  saveAll: '💾 అన్ని మార్పులు సేవ్ చేయి',
    langTitle: 'భాష ప్రాధాన్యత',  langSub: 'మీకు నచ్చిన భాష ఎంచుకోండి',
    profileTitle: 'తల్లిదండ్రుల ప్రొఫైల్', profileSub: 'మీ నమోదు ఖాతా సమాచారం',
    childInfoTitle: 'పిల్లల సమాచారం', childInfoSub: 'నమోదు చేయబడిన పిల్లల ఆరోగ్య ప్రొఫైల్',
    notifTitle: 'నోటిఫికేషన్ సెట్టింగులు', notifSub: 'హెచ్చరికలు నిర్వహించండి',
    secTitle: 'భద్రత', secSub: 'పాస్‌వర్డ్ మార్చు',
    downloadAll: '📥 అన్ని నివేదికలు డౌన్‌లోడ్ చేయి',
    bookAppt: '📅 అపాయింట్‌మెంట్ బుక్', vaccineCard: '💳 టీకా కార్డు',
    setReminder: '🔔 రిమైండర్ సెట్', bookNow: '📅 ఇప్పుడు బుక్',
    checkStatus: 'స్థితి తనిఖీ చేయి →', checkEligibility: 'అర్హత తనిఖీ →',
    nearbyHospitals: '🏥 సమీప ఆసుపత్రులు', searchLocation: 'స్థానం వెతుకు…',
    recordGrowth: '📏 పెరుగుదల నమోదు', weightKg: 'బరువు (కిలో)', heightCm: 'ఎత్తు (సెంమీ)',
    save: 'సేవ్', cancel: 'రద్దు', markDone: 'పూర్తయింది',
    dietPlanFor: 'ఆహార ప్రణాళిక', ageMonths: 'నెలల వయస్సు',
  },
  मराठी: {
    dashboard: '🏠 डॅशबोर्ड',    myChild: '👶 माझे मूल',
    vaccines:  '💉 लसीकरण',      growth:  '📈 वाढ',
    dietPlan:  '🥗 आहार योजना',  schemes: '🏛️ सरकारी योजना',
    reports:   '📋 अहवाल',       notifications: '🔔 सूचना',
    settings:  '⚙️ सेटिंग्ज',
    welcome: 'पुन्हा स्वागत आहे', addChild: 'मूल जोडा',
    bookVaccine: 'लस बुक करा',    logGrowth: 'वाढ नोंदवा',
    downloadReport: 'अहवाल डाउनलोड करा', viewProfile: 'प्रोफाइल पहा',
    healthScore: 'आरोग्य स्कोर',  saveAll: '💾 सर्व बदल जतन करा',
    langTitle: 'भाषा प्राधान्य', langSub: 'आपली पसंदीची भाषा निवडा',
    profileTitle: 'पालक प्रोफाइल', profileSub: 'नोंदणीकृत खाते माहिती',
    childInfoTitle: 'मुलाची माहिती', childInfoSub: 'नोंदणीकृत मुलाचे आरोग्य प्रोफाइल',
    notifTitle: 'सूचना सेटिंग्ज', notifSub: 'अलर्ट व्यवस्थापित करा',
    secTitle: 'सुरक्षा', secSub: 'पासवर्ड बदला',
    downloadAll: '📥 सर्व अहवाल डाउनलोड करा',
    bookAppt: '📅 अपॉइंटमेंट बुक करा', vaccineCard: '💳 लस कार्ड',
    setReminder: '🔔 आठवण सेट करा', bookNow: '📅 आता बुक करा',
    checkStatus: 'स्थिती तपासा →', checkEligibility: 'पात्रता तपासा →',
    nearbyHospitals: '🏥 जवळचे रुग्णालय', searchLocation: 'ठिकाण शोधा…',
    recordGrowth: '📏 वाढ नोंदवा', weightKg: 'वजन (किलो)', heightCm: 'उंची (सेमी)',
    save: 'जतन करा', cancel: 'रद्द करा', markDone: 'पूर्ण करा',
    dietPlanFor: 'आहार योजना', ageMonths: 'महिने वयाचे',
  },
  ગુજરાતી: {
    dashboard: '🏠 ડેશબોર્ડ', myChild: '👶 મારું બાળક', vaccines: '💉 રસીકરણ', growth: '📈 વૃद्धि',
    dietPlan: '🥗 આહાર યોજના', schemes: '🏛️ સરકારી યોજનાઓ', reports: '📋 અહેવાલ', notifications: '🔔 સૂચના',
    settings: '⚙️ સેટિંગ્સ', welcome: 'પાછા આવો', addChild: 'બાળક ઉમેરો', bookVaccine: 'રસી બુક કરો',
    logGrowth: 'વૃद्धि નોંધો', downloadReport: 'અહેવાલ ડાઉનલોડ', viewProfile: 'પ્રોફાઇલ જુઓ',
    healthScore: 'સ્વાસ્થ્ય સ્કોર', saveAll: '💾 બધા ફેરફાર સેવ', langTitle: 'ભાષા પસંદ', langSub: 'ભાષા પસંद કરો',
    profileTitle: 'વાલી પ્રોફાઇલ', profileSub: 'નોંધાયેલ ખાતાની માહિતી',
    childInfoTitle: 'બાળ માહિતી', childInfoSub: 'નોંધાયેલ બાળકની આરોગ્ય પ્રોફાઇલ',
    notifTitle: 'સૂચના સેટિંગ્સ', notifSub: 'ચેतावनी સંચાળો', secTitle: 'સુરક્ષા', secSub: 'પાસવર્ड બદলો',
    downloadAll: '📥 બધા અહેવાલ ડાઉ.', bookAppt: '📅 એપોઇન્ટ બુક', vaccineCard: '💳 રસી કાર્ड',
    setReminder: '🔔 રિminder સેट', bookNow: '📅 હmm બuuk', checkStatus: 'સ્થિ. ◌ →', checkEligibility: 'પાત્ ◌ →',
    nearbyHospitals: '🏥 નjdik હospit', searchLocation: 'Sthan Shodho…',
    recordGrowth: '📏 Vruddhi', weightKg: 'Wajan (kg)', heightCm: 'Unchai (cm)',
    save: 'Save', cancel: 'Raddo', markDone: 'Purn', dietPlanFor: 'Aahar Yojana', ageMonths: 'Mahina',
    loginTitle: 'પાછા આવ્યા', loginSubtitle: 'પ્રવેश ચালু', loginBtn: 'સાઇન ઇન', registerBtn: 'ખાতું બnaao',
    email: 'ઈ-મeil / ফon', phone: 'ফon', password: 'Pasword', fullName: 'Puro Nam',
    selectRole: 'Aapno rol chunai', forgotPassword: 'Pasword bhulaya?', keepSignedIn: 'Me Sign In rakho',
    noAccount: 'Sishu Arogaya ma nava cho?', alreadyAccount: 'Khatu che?', login: 'Login',
    registerTitle: 'Khatu banavo', otpVerify: 'OTP confirm', otpSubtitle: 'Email par OTP dale',
    otpLabel: 'OTP', otpRequired: 'OTP jaruri', verifyLogin: 'Verify karo', backToLogin: 'Login par jao',
    redirecting: 'Redirect...', logout: 'Logout', back: 'Pache', next: 'Aage', loading: 'Load thai rahu che...',
    search: 'Shodho', save2: 'Save', myChildren: 'Mara Bachcha', logVisit: 'Visit nodhao',
    visitHistory: 'Visit itihas', growthRecords: 'Vruddhi Record', vaccinationTracker: 'Rasikaran Tracker',
    malnutritionReport: 'Kuposhad Report', assignedChildren: 'Sopal Bachcha', totalChildren: 'Kul Bachcha',
    healthy: 'Svasth', moderate: 'Madhyam', severe: 'Gambhir', normal: 'Samanya',
    overdue: 'Mudi viti', completed: 'Purn', pending: 'Baki', status: 'Sthiti',
    weight: 'Wajan', height: 'Unchhai', childName: 'Bachcha nu Nam', gender: 'Jati', male: 'Purush', female: 'Stri',
  },
  ಕನ್ನಡ: {
    dashboard: '🏠 ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', myChild: '👶 ನನ್ನ ಮಗು', vaccines: '💉 ಲಸಿಕೆ', growth: '📈 ಬೆಳವಣಿಗೆ',
    dietPlan: '🥗 ಆಹಾರ ಯೋಜನೆ', schemes: '🏛️ ಸರ್ಕಾರಿ ಯೋಜನೆ', reports: '📋 ವರದಿ', notifications: '🔔 ಅಧಿಸೂಚನೆ',
    settings: '⚙️ ಸೆಟ್ಟಿಂಗ್ಸ್', welcome: 'ಮರಳಿ ಸ್ವಾಗತ', addChild: 'ಮಗು ಸೇರಿಸಿ', bookVaccine: 'ಲಸಿಕೆ ಬಳಸಿ',
    logGrowth: 'ಬೆಳವಣಿಗೆ ದಾಖಲು', downloadReport: 'ವರದಿ ಡೌನ್ಲೋಡ್', viewProfile: 'ಪ್ರೊಫೈಲ್ ನೋಡಿ',
    healthScore: 'ಆರೋಗ್ಯ ಅಂಕ', saveAll: '💾 ಉಳಿಸಿ', langTitle: 'ಭಾಷಾ ಆದ್ಯತೆ', langSub: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    profileTitle: 'ಪಾಲಕ ಪ್ರೊಫೈಲ್', profileSub: 'ನೋಂದಾಯಿತ ಖಾತೆ ಮಾಹಿತಿ',
    childInfoTitle: 'ಮಗುವಿನ ಮಾಹಿತಿ', childInfoSub: 'ನೋಂದಾಯಿತ ಮಗುವಿನ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್',
    notifTitle: 'ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್', notifSub: 'ಎಚ್ಚರಿಕೆ ನಿರ್ವಹಿಸಿ', secTitle: 'ಭದ್ರತೆ', secSub: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ',
    downloadAll: '📥 ಎಲ್ಲ ವರದಿ', bookAppt: '📅 ಅಪಾಯಿಂಟ್ಮೆಂಟ್', vaccineCard: '💳 ಲಸಿಕೆ ಕಾರ್ಡ್',
    setReminder: '🔔 ನೆನಪು ಸೆಟ್', bookNow: '📅 ಈಗ ಬಳಸಿ', checkStatus: 'ಸ್ಥಿತಿ ತಪಾಸಿ →', checkEligibility: 'ಅರ್ಹತೆ →',
    nearbyHospitals: '🏥 ಸಮೀಪ ಆಸ್ಪತ್ರೆ', searchLocation: 'ಸ್ಥಳ ಹುಡುಕಿ…',
    recordGrowth: '📏 ಬೆಳವಣಿಗೆ', weightKg: 'ತೂಕ (ಕಿ.ಗ್ರಾ)', heightCm: 'ಎತ್ತರ (ಸೆ.ಮೀ)',
    save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', markDone: 'ಮುಗಿಯಿತು', dietPlanFor: 'ಆಹಾರ ಯೋಜನೆ', ageMonths: 'ತಿಂಗಳ ವಯಸ್ಸು',
    loginTitle: 'ಮರಳಿ ಸ್ವಾಗತ', loginSubtitle: 'ಸೈನ್ ಇನ್ ಮಾಡಿ', loginBtn: 'ಸೈನ್ ಇನ್', registerBtn: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    email: 'ಇಮೇಲ್ / ಫೋನ್', phone: 'ಫೋನ್ ಸಂಖ್ಯೆ', password: 'ಪಾಸ್‌ವರ್ಡ್',
    enterPassword: 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ', fullName: 'ಪೂರ್ಣ ಹೆಸರು', selectRole: 'ಪಾತ್ರ ಆಯ್ಕೆಮಾಡಿ',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?', keepSignedIn: 'ಸೈನ್ ಇನ್ ಉಳಿಸಿ', noAccount: 'ಹೊಸದಾ?',
    alreadyAccount: 'ಖಾತೆ ಇದೆಯಾ?', login: 'ಲಾಗಿನ್', registerTitle: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    otpVerify: 'OTP ಪರಿಶೀಲಿಸಿ', otpLabel: 'OTP', verifyLogin: 'ಪರಿಶೀಲಿಸಿ', backToLogin: 'ಲಾಗಿನ್‌ಗೆ',
    logout: 'ಲಾಗ್ ಔಟ್', save2: 'ಉಳಿಸಿ', back: 'ಹಿಂದೆ', next: 'ಮುಂದೆ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    search: 'ಹುಡುಕಿ', myChildren: 'ನನ್ನ ಮಕ್ಕಳು', logVisit: 'ಭೇಟಿ ದಾಖಲು', visitHistory: 'ಭೇಟಿ ಇತಿಹಾಸ',
    healthy: 'ಆರೋಗ್ಯಕರ', moderate: 'ಮಧ್ಯಮ', severe: 'ತೀವ್ರ', normal: 'ಸಾಮಾನ್ಯ',
    overdue: 'ಗಡಿ ಮೀರಿದ', completed: 'ಪೂರ್ಣ', pending: 'ಬಾಕಿ', status: 'ಸ್ಥಿತಿ',
    weight: 'ತೂಕ', height: 'ಎತ್ತರ', childName: 'ಮಗುವಿನ ಹೆಸರು', gender: 'ಲಿಂಗ', male: 'ಪುರುಷ', female: 'ಮಹಿಳೆ',
  },
  മലയാളം: {
    dashboard: '🏠 ഡാഷ്‌ബോർഡ്', myChild: '👶 എന്റെ കുഞ്ഞ്', vaccines: '💉 വാക്സിൻ', growth: '📈 വളർച്ച',
    dietPlan: '🥗 ഭക്ഷണ പദ്ധതി', schemes: '🏛️ സർക്കാർ പദ്ധതി', reports: '📋 റിപ്പോർട്ട്', notifications: '🔔 അറിയിപ്പ്',
    settings: '⚙️ ക്രമീകരണം', welcome: 'തിരിച്ചെത്തി', addChild: 'കുഞ്ഞിനെ ചേർക്കുക', bookVaccine: 'വാക്സിൻ ബുക്ക്',
    logGrowth: 'വളർച്ച രേഖപ്പെടുത്തൽ', downloadReport: 'റിപ്പോർട്ട് ഡൗൺലോഡ്', viewProfile: 'പ്രൊഫൈൽ കാണുക',
    healthScore: 'ആരോഗ്യ സ്‌കോർ', saveAll: '💾 സേവ് ചെയ്യുക', langTitle: 'ഭാഷ തിരഞ്ഞെടുക്കൽ', langSub: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    profileTitle: 'രക്ഷകർത്താവ് പ്രൊഫൈൽ', profileSub: 'അക്കൗണ്ട് വിവരം',
    childInfoTitle: 'കുട്ടി വിവരം', childInfoSub: 'ആരോഗ്യ പ്രൊഫൈൽ',
    notifTitle: 'അറിയിപ്പ് ക്രമീകരണം', notifSub: 'അലർട്ടുകൾ', secTitle: 'സുരക്ഷ', secSub: 'പാസ്‌വേർഡ് മാറ്റം',
    downloadAll: '📥 എല്ലാ റിപ്പോർട്ടും', bookAppt: '📅 അപ്പോ. ബുക്ക്', vaccineCard: '💳 വാക്സിൻ കാർഡ്',
    setReminder: '🔔 ഓർമ്മ', bookNow: '📅 ഇപ്പോൾ', checkStatus: 'സ്ഥിതി →', checkEligibility: 'യോഗ്യത →',
    nearbyHospitals: '🏥 ആശുപത്രി', searchLocation: 'സ്ഥലം തിരയുക…',
    recordGrowth: '📏 വളർച്ച', weightKg: 'ഭാരം (കി.ഗ്രാം)', heightCm: 'ഉയരം (സെ.മീ)',
    save: 'സേവ്', cancel: 'റദ്ദ്', markDone: 'പൂർണ്ണം', dietPlanFor: 'ഭക്ഷണ പദ്ധതി', ageMonths: 'മാസം',
    loginTitle: 'സ്വാഗതം', loginSubtitle: 'ലോഗിൻ ചെയ്യുക', loginBtn: 'ലോഗിൻ', registerBtn: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    email: 'ഇമെയിൽ / ഫോൺ', phone: 'ഫോൺ നമ്പർ', password: 'പാസ്‌വേർഡ്',
    enterPassword: 'പാസ്‌വേർഡ് ടൈപ്പ്', fullName: 'പൂർണ നാമം', selectRole: 'റോൾ തിരഞ്ഞ.',
    forgotPassword: 'പാസ്‌വേർഡ് മറന്നോ?', keepSignedIn: 'ലോഗിൻ ആകുക', noAccount: 'പുതിയ ഉപയോക്താവോ?',
    alreadyAccount: 'അക്കൗണ്ട് ഉണ്ടോ?', login: 'ലോഗിൻ', registerTitle: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'പരിശോധന', backToLogin: 'ലോഗിൻ',
    logout: 'ലോഗ്ഔട്ട്', back: 'തിരിക്ക്', next: 'അടുത്ത്', loading: 'ലോഡ്…',
    search: 'തിരയുക', myChildren: 'എന്റെ കുട്ടികൾ', logVisit: 'സന്ദർശനം', visitHistory: 'ചരിത്രം',
    healthy: 'ആരോഗ്യകരം', moderate: 'മിതം', severe: 'ഗുരുതരം', normal: 'സാധാരണ',
    overdue: 'കാലഹരണ', completed: 'പൂർത്തി', pending: 'ബാക്കി', status: 'സ്ഥിതി',
    weight: 'ഭാരം', height: 'ഉയരം', childName: 'കുട്ടിയുടെ പേര്', gender: 'ലിംഗം', male: 'ആൺ', female: 'പെൺ',
  },
  ଓଡ଼ିଆ: {
    dashboard: '🏠 ଡ୍ୟାସ୍‌ବୋର୍ଡ', myChild: '👶 ମୋ ଶିଶୁ', vaccines: '💉 ଟୀକା', growth: '📈 ବୃଦ୍ଧି',
    dietPlan: '🥗 ଖାଦ୍ୟ ଯୋଜନା', schemes: '🏛️ ସରକାରୀ ଯୋଜନା', reports: '📋 ରିପୋର୍ଟ', notifications: '🔔 ବିଜ୍ଞପ୍ତି',
    settings: '⚙️ ସେଟିଂ', welcome: 'ପୁଣି ସ୍ୱାଗତ', addChild: 'ଶିଶୁ ଯୋଡ଼', bookVaccine: 'ଟୀକା ବୁକ',
    logGrowth: 'ବୃଦ୍ଧି ଲଗ', downloadReport: 'ରିପୋର୍ଟ ଡାଉ.', viewProfile: 'ପ୍ରୋଫାଇଲ',
    healthScore: 'ସ୍ୱାସ୍ଥ୍ୟ ସ୍କୋର', saveAll: '💾 ସଞ୍ଚୟ', langTitle: 'ଭାଷା', langSub: 'ଭାଷା ବାଛ',
    profileTitle: 'ଅଭିଭାବକ', profileSub: 'ଖାତା ସୂଚନା', childInfoTitle: 'ଶିଶୁ ସୂଚନା', childInfoSub: 'ସ୍ୱାସ୍ଥ୍ୟ',
    notifTitle: 'ବିଜ୍ଞପ୍ତି', notifSub: 'ଆଲର୍ଟ', secTitle: 'ସୁରକ୍ଷା', secSub: 'ପାସୱାର୍ଡ ବଦଳ',
    downloadAll: '📥 ସବୁ ରିପୋ.', bookAppt: '📅 ଅ.ବୁ.', vaccineCard: '💳 ଟୀକା କାର୍ଡ',
    setReminder: '🔔 ମନେ', bookNow: '📅 ବୁକ', checkStatus: 'ସ୍ଥିତି →', checkEligibility: 'ଯୋଗ୍ୟ →',
    nearbyHospitals: '🏥 ଡାକ୍ତରଖାନା', searchLocation: 'ସ୍ଥାନ ଖୋଜ…',
    recordGrowth: '📏 ବୃଦ୍ଧି', weightKg: 'ଓଜନ (କି.ଗ୍ରା)', heightCm: 'ଉଚ୍ଚତା (ସେ.ମି)',
    save: 'ସଞ୍ଚୟ', cancel: 'ବାତିଲ', markDone: 'ସମ୍ପୂର୍ଣ', dietPlanFor: 'ଖାଦ୍ୟ ଯୋ.', ageMonths: 'ମାସ',
    loginTitle: 'ସ୍ୱାଗତ', loginBtn: 'ସାଇନ ଇନ', registerBtn: 'ଖାତା ଖୋଲ', email: 'ଇ.ମେ/ଫୋ', phone: 'ଫୋ.ନ.',
    password: 'ପାସୱାର୍ଡ', fullName: 'ପୂରା ନାମ', selectRole: 'ଭୂମିକା', forgotPassword: 'ପାସ. ଭୁଲି?',
    noAccount: 'ନୂଆ?', alreadyAccount: 'ଖାତା ଅଛି?', login: 'ଲଗ ଇନ', registerTitle: 'ଖାତା ଖୋଲ',
    otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'ଯାଞ୍ଚ', backToLogin: 'ଫେରିଯାଅ',
    logout: 'ବାହାର', back: 'ଫେରି', next: 'ଆଗ', loading: 'ଲୋଡ...',
    search: 'ଖୋଜ', myChildren: 'ମୋ ଶିଶୁ', logVisit: 'ଭ୍ରମଣ', visitHistory: 'ଇତିହାସ',
    healthy: 'ସୁସ୍ଥ', moderate: 'ମଧ୍ୟ', severe: 'ଗୁରୁ', normal: 'ସ୍ବାଭାବ',
    overdue: 'ସମ ପଚ', completed: 'ସମ୍ପ', pending: 'ବାକି', status: 'ସ୍ଥ',
    weight: 'ଓଜନ', height: 'ଉଚ୍ଚ', childName: 'ନାମ', gender: 'ଲିଙ୍ଗ', male: 'ପୁ', female: 'ସ୍ତ୍ରୀ',
  },
  অসমীয়া: {
    dashboard: '🏠 ডেশ্ববোর্ড', myChild: '👶 মোৰ শিশু', vaccines: '💉 ছিকা', growth: '📈 বিকাশ',
    dietPlan: '🥗 খাদ্য পৰিকল্পনা', schemes: '🏛️ চৰকাৰী আঁচনি', reports: '📋 ৰিপোৰ্ট', notifications: '🔔 জাননী',
    settings: '⚙️ ছেটিং', welcome: 'আকৌ স্বাগতম', addChild: 'শিশু যোগ কৰক', bookVaccine: 'ছিকা বুক কৰক',
    logGrowth: 'বিকাশ ৰেকৰ্ড', downloadReport: 'ৰিপোৰ্ট ডাউ.', viewProfile: 'প্ৰ\'ফাইল',
    healthScore: 'স্বাস্থ্য স্কোৰ', saveAll: '💾 সংৰক্ষণ', langTitle: 'ভাষা', langSub: 'ভাষা বাছক',
    profileTitle: 'অভিভাৱক প্ৰ\'ফাইল', profileSub: 'একাউণ্ট তথ্য',
    childInfoTitle: 'শিশুৰ তথ্য', childInfoSub: 'স্বাস্থ্য প্ৰ\'ফাইল',
    notifTitle: 'জাননী', notifSub: 'সতৰ্কতা', secTitle: 'সুৰক্ষা', secSub: 'পাছৱৰ্ড সলাওক',
    downloadAll: '📥 সকলো ৰিপো.', bookAppt: '📅 এপোয়', vaccineCard: '💳 ছিকা কাৰ্ড',
    setReminder: '🔔 মনে পেলাওক', bookNow: '📅 বুক', checkStatus: 'স্থিতি →', checkEligibility: 'যোগ্যতা →',
    nearbyHospitals: '🏥 চিকিৎসালয়', searchLocation: 'ঠাই বিচাৰক…',
    recordGrowth: '📏 বিকাশ', weightKg: 'ওজন (কি.গ্ৰা)', heightCm: 'উচ্চতা (চে.মি)',
    save: 'সংৰক্ষণ', cancel: 'বাতিল', markDone: 'সম্পূৰ্ণ', dietPlanFor: 'খাদ্য', ageMonths: 'মাহ',
    loginTitle: 'স্বাগতম', loginBtn: 'ছাইন ইন', registerBtn: 'একাউণ্ট খোলক', email: 'ইমেইল/ফোন',
    phone: 'ফোন', password: 'পাছৱৰ্ড', fullName: 'পুৰা নাম', selectRole: 'ভূমিকা',
    forgotPassword: 'পাছ. পাহৰিলে?', noAccount: 'নতুন?', alreadyAccount: 'একাউণ্ট আছে?', login: 'লগইন',
    registerTitle: 'একাউণ্ট বনাওক', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'নিশ্চিত',
    backToLogin: 'লগইনলৈ', logout: 'বাহিৰ', back: 'পিছে', next: 'আগ', loading: 'লোড হৈছে...',
    search: 'বিচাৰক', myChildren: 'মোৰ শিশু', logVisit: 'ভ্ৰমণ', visitHistory: 'ইতিহাস',
    healthy: 'সুস্থ', moderate: 'মধ্যম', severe: 'গুৰুত্বপূৰ্ণ', normal: 'সাধাৰণ',
    status: 'অৱস্থা', weight: 'ওজন', height: 'উচ্চতা', childName: 'নাম', gender: 'লিংগ', male: 'পুৰুষ', female: 'মহিলা',
  },
  اردو: {
    dashboard: '🏠 ڈیش بورڈ', myChild: '👶 میرا بچہ', vaccines: '💉 ویکسین', growth: '📈 نشوونما',
    dietPlan: '🥗 غذائی منصوبہ', schemes: '🏛️ سرکاری اسکیم', reports: '📋 رپورٹ', notifications: '🔔 اطلاع',
    settings: '⚙️ ترتیبات', welcome: 'واپس خوش آمدید', addChild: 'بچہ شامل', bookVaccine: 'ویکسین بک',
    logGrowth: 'نشوونما ریکارڈ', downloadReport: 'رپورٹ ڈاؤن لوڈ', viewProfile: 'پروفائل',
    healthScore: 'صحت اسکور', saveAll: '💾 محفوظ', langTitle: 'زبان', langSub: 'زبان منتخب کریں',
    profileTitle: 'والدین پروفائل', profileSub: 'اکاؤنٹ معلومات',
    childInfoTitle: 'بچے کی معلومات', childInfoSub: 'صحت پروفائل',
    notifTitle: 'اطلاع ترتیبات', notifSub: 'الرٹ', secTitle: 'سیکیورٹی', secSub: 'پاس ورڈ تبدیل',
    downloadAll: '📥 تمام رپورٹ', bookAppt: '📅 اپوائنٹمنٹ', vaccineCard: '💳 ویکسین کارڈ',
    setReminder: '🔔 یاد دہانی', bookNow: '📅 ابھی', checkStatus: 'حالت →', checkEligibility: 'اہلیت →',
    nearbyHospitals: '🏥 ہسپتال', searchLocation: 'جگہ تلاش…',
    recordGrowth: '📏 نشوونما', weightKg: 'وزن (کلو)', heightCm: 'قد (سینٹی)',
    save: 'محفوظ', cancel: 'منسوخ', markDone: 'مکمل', dietPlanFor: 'غذائی منصوبہ', ageMonths: 'ماہ',
    loginTitle: 'خوش آمدید', loginSubtitle: 'سائن ان کریں', loginBtn: 'سائن ان', registerBtn: 'اکاؤنٹ بنائیں',
    email: 'ای میل / فون', phone: 'فون نمبر', password: 'پاس ورڈ',
    enterPassword: 'پاس ورڈ درج کریں', fullName: 'پورا نام', selectRole: 'کردار منتخب',
    forgotPassword: 'پاس ورڈ بھولے؟', keepSignedIn: 'سائن ان رہیں', noAccount: 'نئے ہیں؟',
    alreadyAccount: 'اکاؤنٹ ہے؟', login: 'لاگ ان', registerTitle: 'اکاؤنٹ بنائیں',
    otpVerify: 'OTP تصدیق', otpLabel: 'OTP', verifyLogin: 'تصدیق', backToLogin: 'لاگ ان',
    redirecting: 'منتقل ہو رہے ہیں…', logout: 'لاگ آؤٹ', back: 'واپس', next: 'آگے', loading: 'لوڈ…',
    search: 'تلاش', myChildren: 'میرے بچے', logVisit: 'دورہ', visitHistory: 'تاریخ',
    healthy: 'صحت مند', moderate: 'متوسط', severe: 'شدید', normal: 'معمول',
    overdue: 'مدت گزر', completed: 'مکمل', pending: 'باقی', status: 'حالت',
    weight: 'وزن', height: 'قد', childName: 'بچے کا نام', gender: 'جنس', male: 'مرد', female: 'عورت',
  },
  नेपाली: {
    dashboard: '🏠 ड्यासबोर्ड', myChild: '👶 मेरो बच्चा', vaccines: '💉 खोप', growth: '📈 विकास',
    dietPlan: '🥗 खाना योजना', schemes: '🏛️ सरकारी योजना', reports: '📋 प्रतिवेदन', notifications: '🔔 सूचना',
    settings: '⚙️ सेटिङ', welcome: 'फिर्ता स्वागत', addChild: 'बच्चा थप्नुस्', bookVaccine: 'खोप बुक',
    logGrowth: 'विकास लग', downloadReport: 'रिपोर्ट डाउ.', viewProfile: 'प्रोफाइल',
    healthScore: 'स्वास्थ्य स्कोर', saveAll: '💾 सुरक्षित', langTitle: 'भाषा', langSub: 'भाषा छान्नुस्',
    profileTitle: 'अभिभावक', profileSub: 'खाता जानकारी', childInfoTitle: 'बच्चाको जानकारी', childInfoSub: 'स्वास्थ्य',
    notifTitle: 'सूचना', notifSub: 'अलर्ट', secTitle: 'सुरक्षा', secSub: 'पासवर्ड बदल्नुस्',
    downloadAll: '📥 सबै', bookAppt: '📅 बुक', vaccineCard: '💳 खोप कार्ड',
    setReminder: '🔔 सम्झनु', bookNow: '📅 बुक', checkStatus: 'स्थिति →', checkEligibility: 'योग्यता →',
    nearbyHospitals: '🏥 अस्पताल', searchLocation: 'ठाउँ खोज्नुस्…',
    recordGrowth: '📏 विकास', weightKg: 'तौल (किलो)', heightCm: 'उचाइ (सेमी)',
    save: 'सुरक्षित', cancel: 'रद्द', markDone: 'पूर्ण', dietPlanFor: 'खाना योजना', ageMonths: 'महिना',
    loginTitle: 'स्वागत', loginBtn: 'साइन इन', registerBtn: 'खाता खोल्नुस्', email: 'इमेल/फोन',
    phone: 'फोन', password: 'पासवर्ड', fullName: 'पूरा नाम', selectRole: 'भूमिका',
    forgotPassword: 'पास. बिर्स्यो?', noAccount: 'नयाँ?', alreadyAccount: 'खाता छ?', login: 'लगइन',
    registerTitle: 'खाता बनाउनुस्', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'प्रमाणित',
    backToLogin: 'लगइन', logout: 'बाहिर', back: 'पछि', next: 'अगाडि', loading: 'लोड हुदैछ...',
    search: 'खोज्नुस्', myChildren: 'मेरा बच्चाहरू', logVisit: 'भ्रमण', visitHistory: 'इतिहास',
    healthy: 'स्वस्थ', moderate: 'मध्यम', severe: 'गम्भीर', normal: 'सामान्य',
    status: 'स्थिति', weight: 'तौल', height: 'उचाइ', childName: 'नाम', gender: 'लिङ्ग', male: 'पुरुष', female: 'महिला',
  },
  মৈতৈলোন্: {
    dashboard: '🏠 ডেশ্ববোর্ড', myChild: '👶 ঐগি নুপামচা', vaccines: '💉 ইনজেকশন', growth: '📈 চাউখৎ',
    dietPlan: '🥗 চাউবা থাজবা', schemes: '🏛️ সরকারগি প্লান', reports: '📋 রিপোর্ট', notifications: '🔔 খঙহনবা',
    settings: '⚙️ সেটিং', welcome: 'পুনসি লৌখিবা', addChild: 'নুপামচা থেম্বিয়ু', bookVaccine: 'ইনজেকশন বুক',
    logGrowth: 'চাউখৎ লগ', downloadReport: 'রিপোর্ট ডাউ', viewProfile: 'প্রোফাইল',
    healthScore: 'হেলথ স্কোর', saveAll: '💾 লৌখিবা', langTitle: 'মশিং', langSub: 'মশিং থেম্বিয়ু',
    profileTitle: 'মাপাল', profileSub: 'একাউন্ট', childInfoTitle: 'নুপামচা', childInfoSub: 'হেলথ',
    notifTitle: 'নোটিফিকেশন', notifSub: 'এলার্ট', secTitle: 'সিকিউরিটি', secSub: 'পাসওয়ার্ড',
    downloadAll: '📥 অমরা রিপোর্ট', bookAppt: '📅 বুক', vaccineCard: '💳 ইনজেকশন কার্ড',
    setReminder: '🔔 মনে কর', bookNow: '📅 বুক', checkStatus: 'স্টেটাস →', checkEligibility: 'যোগ্যতা →',
    nearbyHospitals: '🏥 হাসপাতাল', searchLocation: 'জায়গা খোজ…',
    recordGrowth: '📏 চাউখৎ', weightKg: 'নাউবা (কিলো)', heightCm: 'লৈবাক (সেমি)',
    save: 'লৌখিবা', cancel: 'কান্সেল', markDone: 'পূর্ণ', dietPlanFor: 'চাউবা', ageMonths: 'থা',
    loginTitle: 'লৌখিবা', loginBtn: 'সাইন ইন', registerBtn: 'একাউন্ট', email: 'ইমেইল', phone: 'ফোন',
    password: 'পাসওয়ার্ড', fullName: 'নাম', selectRole: 'রোল', login: 'লগইন',
    registerTitle: 'একাউন্ট', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'চেক', backToLogin: 'লগইন',
    logout: 'বাহিরে', back: 'পিছে', next: 'আগে', loading: 'লোড...',
    search: 'খোজ', myChildren: 'নুপামচাশিং', healthy: 'চাউখৎ', moderate: 'মধ্যম', severe: 'গুরুত্বপূর্ণ',
    status: 'স্টেটাস', weight: 'নাউবা', height: 'লৈবাক', childName: 'নাম', gender: 'ইনাপ', male: 'মাচা', female: 'মলোন',
  },
  संस्कृत: {
    dashboard: '🏠 सारणी', myChild: '👶 मम बालकः', vaccines: '💉 टीकाकरणम्', growth: '📈 वृद्धिः',
    dietPlan: '🥗 आहारयोजना', schemes: '🏛️ शासकीयाः योजनाः', reports: '📋 विवरणम्', notifications: '🔔 सूचना',
    settings: '⚙️ व्यवस्था', welcome: 'पुनः स्वागतम्', addChild: 'बालकं योजयतु', bookVaccine: 'टीका',
    logGrowth: 'वृद्धिः', downloadReport: 'विवरणम्', viewProfile: 'परिचयः',
    healthScore: 'आरोग्यमूल्यम्', saveAll: '💾 सर्वं रक्ष', langTitle: 'भाषा', langSub: 'भाषां वृणुत',
    profileTitle: 'जनकः', profileSub: 'खाता', childInfoTitle: 'बालकः', childInfoSub: 'आरोग्यम्',
    notifTitle: 'सूचना', notifSub: 'सावधानम्', secTitle: 'सुरक्षा', secSub: 'गुप्तशब्दः',
    downloadAll: '📥 सर्वम्', bookAppt: '📅 नियुक्ति', vaccineCard: '💳 टीकापत्र',
    setReminder: '🔔 स्मरण', bookNow: '📅 अधुना', checkStatus: 'स्थितिः →', checkEligibility: 'योग्यता →',
    nearbyHospitals: '🏥 चिकित्सालयम्', searchLocation: 'स्थानं गवेषयतु…',
    recordGrowth: '📏 वृद्धिः', weightKg: 'भारः (किलो)', heightCm: 'उच्चता (सेमि)',
    save: 'रक्षतु', cancel: 'रद्दीकरोतु', markDone: 'सम्पूर्णम्', dietPlanFor: 'आहारः', ageMonths: 'मासाः',
    loginTitle: 'स्वागतम्', loginBtn: 'प्रवेशः', registerBtn: 'निबन्धनम्', email: 'विद्युत्पत्रम्',
    phone: 'दूरवाणी', password: 'गुप्तशब्दः', fullName: 'पूर्णनाम', selectRole: 'भूमिका',
    forgotPassword: 'गुप्तशब्दः?', noAccount: 'नूतनः?', alreadyAccount: 'खाता?', login: 'प्रवेशः',
    registerTitle: 'निबन्धनम्', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'सत्यापनम्', backToLogin: 'प्रवेशः',
    logout: 'निर्गमनम्', back: 'पुरत', next: 'अग्रे', loading: 'प्रतीक्षतु…',
    search: 'अन्वेषणम्', myChildren: 'मम बालकाः', healthy: 'आरोग्यम्', moderate: 'मध्यमम्', severe: 'गुरुतरम्',
    status: 'स्थितिः', weight: 'भारः', height: 'उच्चता', childName: 'नाम', gender: 'लिंगम्', male: 'पुरुषः', female: 'स्त्री',
  },
  मैथिली: {
    dashboard: '🏠 डैशबोर्ड', myChild: '👶 हमर बच्चा', vaccines: '💉 टीकाकरण', growth: '📈 विकास',
    dietPlan: '🥗 आहार योजना', schemes: '🏛️ सरकारी योजना', reports: '📋 रिपोर्ट', notifications: '🔔 सूचना',
    settings: '⚙️ सेटिंग', welcome: 'पुनः स्वागत', addChild: 'बच्चा जोड़ू', bookVaccine: 'टीका',
    logGrowth: 'विकास', downloadReport: 'रिपोर्ट', viewProfile: 'प्रोफाइल',
    healthScore: 'स्वास्थ्य स्कोर', saveAll: '💾 सहेजू', langTitle: 'भाषा', langSub: 'भाषा चुनू',
    profileTitle: 'माता-पिता', profileSub: 'खाता', childInfoTitle: 'बच्चाक जानकारी', childInfoSub: 'स्वास्थ्य',
    notifTitle: 'सूचना', notifSub: 'अलर्ट', secTitle: 'सुरक्षा', secSub: 'पासवर्ड बदलू',
    downloadAll: '📥 सभ', bookAppt: '📅 बुक', vaccineCard: '💳 टीका कार्ड',
    setReminder: '🔔 याद', bookNow: '📅 बुक', checkStatus: 'स्थिति →', checkEligibility: 'पात्रता →',
    nearbyHospitals: '🏥 अस्पताल', searchLocation: 'जगह खोजू…',
    recordGrowth: '📏 विकास', weightKg: 'वजन (किलो)', heightCm: 'ऊंचाई (सेमी)',
    save: 'सहेजू', cancel: 'रद्द', markDone: 'पूर्ण', dietPlanFor: 'आहार', ageMonths: 'महीना',
    loginTitle: 'स्वागत', loginBtn: 'साइन इन', registerBtn: 'खाता खोलू', email: 'ईमेल/फोन',
    phone: 'फोन', password: 'पासवर्ड', fullName: 'पूरा नाम', selectRole: 'भूमिका',
    forgotPassword: 'पास. भूलि?', noAccount: 'नया?', alreadyAccount: 'खाता छैक?', login: 'लॉगिन',
    registerTitle: 'खाता बनाउ', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'सत्यापित', backToLogin: 'लॉगिन',
    logout: 'बाहर', back: 'पाछू', next: 'आगां', loading: 'लोड...',
    search: 'खोजू', myChildren: 'हमर बच्चा', healthy: 'स्वस्थ', moderate: 'मध्यम', severe: 'गंभीर',
    status: 'स्थिति', weight: 'वजन', height: 'ऊंचाई', childName: 'नाम', gender: 'लिंग', male: 'पुरुष', female: 'महिला',
  },
  डोगरी: {
    dashboard: '🏠 डैशबोर्ड', myChild: '👶 मेरा बच्चा', vaccines: '💉 टीकाकरण', growth: '📈 विकास',
    dietPlan: '🥗 खाने दी योजना', schemes: '🏛️ सरकारी योजनाएं', reports: '📋 रिपोर्ट', notifications: '🔔 सूचना',
    settings: '⚙️ सेटिंग', welcome: 'वापस स्वागत ऐ', addChild: 'बच्चा जोड़ो', bookVaccine: 'टीका',
    logGrowth: 'विकास', downloadReport: 'रिपोर्ट', viewProfile: 'प्रोफाइल',
    healthScore: 'सेहत स्कोर', saveAll: '💾 सेव', langTitle: 'भाशा', langSub: 'भाशा चुनो',
    profileTitle: 'माँ-बाप', profileSub: 'खाता', childInfoTitle: 'बच्चे दी जानकारी', childInfoSub: 'सेहत',
    notifTitle: 'सूचना', notifSub: 'अलर्ट', secTitle: 'सुरक्षा', secSub: 'पासवर्ड',
    downloadAll: '📥 सारे', bookAppt: '📅 बुक', vaccineCard: '💳 टीका कार्ड',
    setReminder: '🔔 याद', bookNow: '📅 बुक', checkStatus: 'स्थिति →', checkEligibility: 'पात्रता →',
    nearbyHospitals: '🏥 अस्पताल', searchLocation: 'जगह लब्भो…',
    recordGrowth: '📏 विकास', weightKg: 'बोझ (किलो)', heightCm: 'लम्बाई (सेमी)',
    save: 'सेव', cancel: 'रद्द', markDone: 'पूरा', dietPlanFor: 'खाना', ageMonths: 'महीना',
    loginTitle: 'स्वागत ऐ', loginBtn: 'लॉग इन', registerBtn: 'खाता बनाओ', email: 'ईमेल/फोन',
    phone: 'फोन', password: 'पासवर्ड', fullName: 'पूरा नाम', selectRole: 'भूमिका',
    forgotPassword: 'पास. भुल्लि?', noAccount: 'नया?', alreadyAccount: 'खाता ऐ?', login: 'लॉगिन',
    registerTitle: 'खाता बनाओ', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'पक्का', backToLogin: 'लॉगिन',
    logout: 'बाहर', back: 'पिच्छे', next: 'अग्गे', loading: 'लोड...',
    search: 'लब्भो', myChildren: 'मेरे बच्चे', healthy: 'तंदुरुस्त', moderate: 'ठीक', severe: 'गंभीर',
    status: 'हालत', weight: 'बोझ', height: 'लम्बाई', childName: 'नाम', gender: 'लिंग', male: 'मर्द', female: 'औरत',
  },
  कोंकणी: {
    dashboard: '🏠 डॅशबोर्ड', myChild: '👶 माझो भुरगो', vaccines: '💉 लसीकरण', growth: '📈 वाढ',
    dietPlan: '🥗 आहार येवजण', schemes: '🏛️ सरकारी येवजणी', reports: '📋 अहवाल', notifications: '🔔 सूचना',
    settings: '⚙️ सेटिंग', welcome: 'परत येवकार', addChild: 'भुरगो घाला', bookVaccine: 'लस',
    logGrowth: 'वाढ', downloadReport: 'अहवाल', viewProfile: 'प्रोफाइल',
    healthScore: 'आरोग्य गुण', saveAll: '💾 राखात', langTitle: 'भास', langSub: 'भास निवडात',
    profileTitle: 'आवय-बाप', profileSub: 'खाते', childInfoTitle: 'भुरग्याची माहिती', childInfoSub: 'आरोग्य',
    notifTitle: 'सूचना', notifSub: 'इशारो', secTitle: 'सुरक्षा', secSub: 'पासवर्ड',
    downloadAll: '📥 सगळे', bookAppt: '📅 बुक', vaccineCard: '💳 लस कार्ड',
    setReminder: '🔔 आठव', bookNow: '📅 बुक', checkStatus: 'स्थिती →', checkEligibility: 'पात्रता →',
    nearbyHospitals: '🏥 इस्पितळ', searchLocation: 'जागो सोद…',
    recordGrowth: '📏 वाढ', weightKg: 'वजन (किलो)', heightCm: 'उंची (सेमी)',
    save: 'राखात', cancel: 'रद्द', markDone: 'पूर्ण', dietPlanFor: 'आहार', ageMonths: 'म्हयने',
    loginTitle: 'येवकार', loginBtn: 'साइन इन', registerBtn: 'खाते काड', email: 'ईमेल/फोन',
    phone: 'फोन', password: 'पासवर्ड', fullName: 'पुरो नाव', selectRole: 'भूमिका',
    forgotPassword: 'पास. विसरलो?', noAccount: 'नवो?', alreadyAccount: 'खाते आसा?', login: 'लॉगिन',
    registerTitle: 'खाते काड', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'तपासात', backToLogin: 'लॉगिन',
    logout: 'भाइर', back: 'फाटीं', next: 'फुडें', loading: 'लोड...',
    search: 'सोद', myChildren: 'माझे भुरगे', healthy: 'तंदुरुस्त', moderate: 'मध्यम', severe: 'गंभीर',
    status: 'स्थिती', weight: 'वजन', height: 'उंची', childName: 'नाव', gender: 'लिंग', male: 'दादलो', female: 'बायल',
  },
  सिन्धी: {
    dashboard: '🏠 ڊيش بورڊ', myChild: '👶 منھنجو ٻار', vaccines: '💉 ويڪسين', growth: '📈 واڌ',
    dietPlan: '🥗 کاڌي جو منصوبو', schemes: '🏛️ سرڪاري اسڪيم', reports: '📋 رپورٽ', notifications: '🔔 خبر',
    settings: '⚙️ سيٽنگ', welcome: 'واپس ڀلي آيا', addChild: 'ٻار شامل ڪريو', bookVaccine: 'ويڪسين',
    logGrowth: 'واڌ', downloadReport: 'رپورٽ', viewProfile: 'پروفائل',
    healthScore: 'صحت اسڪور', saveAll: '💾 محفوظ', langTitle: 'ٻولي', langSub: 'ٻولي چونڊيو',
    profileTitle: 'والدين', profileSub: 'اڪائونٽ', childInfoTitle: 'ٻار جي ڄاڻ', childInfoSub: 'صحت',
    notifTitle: 'خبر', notifSub: 'الرٽ', secTitle: 'سيڪيورٽي', secSub: 'پاسورڊ',
    downloadAll: '📥 سڀ', bookAppt: '📅 بک', vaccineCard: '💳 ويڪسين ڪارڊ',
    setReminder: '🔔 ياد', bookNow: '📅 ھاڻي', checkStatus: 'حالت →', checkEligibility: 'لائق →',
    nearbyHospitals: '🏥 اسپتال', searchLocation: 'جڳھ ڳوليو…',
    recordGrowth: '📏 واڌ', weightKg: 'وزن (ڪلو)', heightCm: 'قد (سينٽي)',
    save: 'محفوظ', cancel: 'منسوخ', markDone: 'مڪمل', dietPlanFor: 'کاڌو', ageMonths: 'مهينا',
    loginTitle: 'ڀلي آيا', loginBtn: 'داخل ٿيو', registerBtn: 'اڪائونٽ ٺاھيو', email: 'اي ميل/فون',
    phone: 'فون', password: 'پاسورڊ', fullName: 'پورو نالو', selectRole: 'ڪردار',
    forgotPassword: 'پاس. وساريو؟', noAccount: 'نئون؟', alreadyAccount: 'اڪائونٽ آھي؟', login: 'لاگ ان',
    registerTitle: 'اڪائونٽ ٺاھيو', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'تصديق', backToLogin: 'لاگ ان',
    logout: 'ٻاھر', back: 'پوئتي', next: 'اڳتي', loading: 'لوڊ...',
    search: 'ڳوليو', myChildren: 'منھنجا ٻار', healthy: 'صحتمند', moderate: 'وچولو', severe: 'سنگين',
    status: 'حالت', weight: 'وزن', height: 'قد', childName: 'نالو', gender: 'جنس', male: 'مرد', female: 'عورت',
  },
  बड़ो: {
    dashboard: '🏠 ডেশ্ববোর্ড', myChild: '👶 ঐনি नुसुं', vaccines: '💉 টিকা', growth: '📈 बादि',
    dietPlan: '🥗 खाबো-दाबो', schemes: '🏛️ सरकारनि', reports: '📋 रिपोर्ट', notifications: '🔔 खबर',
    settings: '⚙️ सेटिंग', welcome: 'देरसे गैया', addChild: 'नुसुं थेम', bookVaccine: 'টিকা',
    logGrowth: 'बादि', downloadReport: 'রিপোর্ট', viewProfile: 'প্রোফাইল',
    healthScore: 'Health Score', saveAll: '💾 Save', langTitle: 'मोन', langSub: 'मोन थेम',
    profileTitle: 'अबा-आम', profileSub: 'Account', childInfoTitle: 'नुसुं', childInfoSub: 'Health',
    notifTitle: 'खबर', notifSub: 'Alert', secTitle: 'Security', secSub: 'Password',
    downloadAll: '📥 सबाय', bookAppt: '📅 बुक', vaccineCard: '💳 টিকা কার্ড',
    setReminder: '🔔 याद', bookNow: '📅 बुक', checkStatus: 'Status →', checkEligibility: 'Yogy →',
    nearbyHospitals: '🏥 हस्पताल', searchLocation: 'जग खोज…',
    recordGrowth: '📏 बादि', weightKg: 'बोखोम (किलो)', heightCm: 'लाम्बि (सेमि)',
    save: 'Save', cancel: 'रद्द', markDone: 'सिमाङ', dietPlanFor: 'खाबो', ageMonths: 'माह',
    loginTitle: 'गैया', loginBtn: 'Login', registerBtn: 'Account', email: 'Email', phone: 'Phone',
    password: 'Password', fullName: 'नाम', selectRole: 'Role', login: 'Login',
    registerTitle: 'Account', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'OK', backToLogin: 'Login',
    logout: 'Logout', back: 'Back', next: 'Next', loading: 'Load...',
    search: 'खोज', myChildren: 'ऐनि नुसुंफोर', healthy: 'अनाय', moderate: 'मध्यम', severe: 'गुरुत',
    status: 'हाल', weight: 'बोखोम', height: 'लाम्बि', childName: 'नाम', gender: 'जाति', male: 'हार्था', female: 'हालि',
  },
  'ᱥᱟᱱᱛᱟᱲᱤ': {
    dashboard: '🏠 ᱰᱮᱥᱵᱚᱨᱰ', myChild: '👶 ᱟᱢᱟᱜ ᱯᱤᱞᱪᱩ', vaccines: '💉 ᱴᱤᱠᱟ', growth: '📈 ᱵᱟᱲᱟᱭ',
    dietPlan: '🥗 ᱮᱛᱚᱢ', schemes: '🏛️ ᱥᱚᱨᱠᱟᱨ', reports: '📋 ᱨᱤᱯᱚᱨᱴ', notifications: '🔔 ᱥᱩᱪᱮᱛ',
    settings: '⚙️ ᱥᱮᱴᱤᱝ', welcome: 'ᱦᱩᱲᱩ ᱚᱠᱟ', addChild: 'ᱯᱤᱞᱪᱩ', bookVaccine: 'ᱴᱤᱠᱟ',
    logGrowth: 'ᱵᱟᱲᱟᱭ', downloadReport: 'ᱨᱤᱯᱚᱨᱴ', viewProfile: 'ᱯᱨᱚᱯᱷᱟᱭᱞ',
    healthScore: 'ᱥᱮᱦᱮᱛ', saveAll: '💾 ᱨᱟᱠᱷᱟ', langTitle: 'ᱯᱟᱸᱛᱮ', langSub: 'ᱯᱟᱸᱛᱮ ᱪᱟᱞᱟᱜ',
    profileTitle: 'ᱟᱹᱯᱩ', profileSub: 'Account', childInfoTitle: 'ᱯᱤᱞᱪᱩ', childInfoSub: 'ᱥᱮᱦᱮᱛ',
    notifTitle: 'ᱥᱩᱪᱮᱛ', notifSub: 'Alert', secTitle: 'Security', secSub: 'Password',
    downloadAll: '📥 ᱥᱟᱱᱟᱢ', bookAppt: '📅 ᱵᱩᱠ', vaccineCard: '💳 ᱴᱤᱠᱟ ᱠᱟᱨᱰ',
    setReminder: '🔔 ᱢᱮᱛᱟᱜ', bookNow: '📅 ᱵᱩᱠ', checkStatus: 'ᱦᱩᱲᱩ →', checkEligibility: 'ᱡᱚᱜ →',
    nearbyHospitals: '🏥 ᱦᱚᱥᱯᱤᱴᱟᱞ', searchLocation: 'ᱡᱟᱭᱜᱟ…',
    recordGrowth: '📏 ᱵᱟᱲᱟᱭ', weightKg: 'ᱵᱳᱡᱷᱚ (ᱠᱤᱞᱚ)', heightCm: 'ᱫᱷᱟᱹᱵ (ᱥᱮᱢᱤ)',
    save: 'ᱨᱟᱠᱷᱟ', cancel: 'ᱵᱟᱛᱤᱞ', markDone: 'ᱯᱩᱨᱟ', dietPlanFor: 'ᱮᱛᱚᱢ', ageMonths: 'ᱪᱟᱸᱫᱚ',
    loginTitle: 'ᱢᱤᱫ ᱦᱩᱲᱩ', loginBtn: 'ᱚᱪᱳᱜ', registerBtn: 'Account', email: 'Email', phone: 'Phone',
    password: 'Password', fullName: 'ᱩᱠᱩᱞ ᱩᱱᱤ', selectRole: 'ᱠᱟᱢ',
    login: 'ᱚᱪᱳᱜ', registerTitle: 'Account', otpVerify: 'OTP', otpLabel: 'OTP',
    verifyLogin: 'ᱪᱮᱠ', backToLogin: 'ᱚᱪᱳᱜ', logout: 'ᱵᱟᱦᱨᱮ', back: 'ᱦᱟᱹᱴᱤᱧ', next: 'ᱟᱜᱟ', loading: 'ᱞᱚᱰ...',
    search: 'ᱪᱷᱟᱸᱵ', myChildren: 'ᱟᱢᱟᱜ ᱯᱤᱞᱪᱩ', healthy: 'ᱟᱰᱟᱜ', moderate: 'ᱢᱤᱫ', severe: 'ᱜᱩᱨᱩ',
    status: 'ᱦᱩᱲᱩ', weight: 'ᱵᱳᱡᱷᱚ', height: 'ᱫᱷᱟᱹᱵ', childName: 'ᱩᱱᱤ', gender: 'ᱡᱟᱹᱛᱤ', male: 'ᱦᱳᱲ', female: 'ᱮᱬᱮᱜ',
  },
  कश्मीरी: {
    dashboard: '🏠 ڈیش بورڈ', myChild: '👶 میٚ اَسہ', vaccines: '💉 ویکسین', growth: '📈 وادھ',
    dietPlan: '🥗 کھانہٕ منصوبہ', schemes: '🏛️ سرکاری اسکیم', reports: '📋 رپورٹ', notifications: '🔔 خبر',
    settings: '⚙️ سیٹنگ', welcome: 'واپس ییہ', addChild: 'اَسہ تھاوو', bookVaccine: 'ویکسین',
    logGrowth: 'وادھ', downloadReport: 'رپورٹ', viewProfile: 'پروفائل',
    healthScore: 'صحت اسکور', saveAll: '💾 محفوظ', langTitle: 'زبان', langSub: 'زبان چُنو',
    profileTitle: 'والدین', profileSub: 'اکاؤنٹ', childInfoTitle: 'اَسہ بابت', childInfoSub: 'صحت',
    notifTitle: 'خبر', notifSub: 'الرٹ', secTitle: 'حفاظت', secSub: 'پاسورڈ',
    downloadAll: '📥 سارے', bookAppt: '📅 بک', vaccineCard: '💳 ویکسین کارڈ',
    setReminder: '🔔 یاد', bookNow: '📅 ہنے', checkStatus: 'حالت →', checkEligibility: 'لائق →',
    nearbyHospitals: '🏥 اسپتال', searchLocation: 'جائی لبو…',
    recordGrowth: '📏 وادھ', weightKg: 'وزن (کلو)', heightCm: 'قد (سینٹی)',
    save: 'محفوظ', cancel: 'منسوخ', markDone: 'مکمل', dietPlanFor: 'کھانہ', ageMonths: 'ماہ',
    loginTitle: 'ییہ گیے', loginBtn: 'داخل', registerBtn: 'اکاؤنٹ', email: 'ای میل/فون',
    phone: 'فون', password: 'پاسورڈ', fullName: 'پورہ ناو', selectRole: 'کِردار',
    forgotPassword: 'پاس. یاد نہ؟', noAccount: 'نیو؟', alreadyAccount: 'اکاؤنٹ چھا؟', login: 'لاگ ان',
    registerTitle: 'اکاؤنٹ بناوو', otpVerify: 'OTP', otpLabel: 'OTP', verifyLogin: 'تصدیق', backToLogin: 'لاگ ان',
    logout: 'باہر', back: 'واپس', next: 'اگیے', loading: 'لوڈ...',
    search: 'لبو', myChildren: 'میٚ اَسہ', healthy: 'تندرست', moderate: 'وچکار', severe: 'سنگین',
    status: 'حالت', weight: 'وزن', height: 'قد', childName: 'ناو', gender: 'جنس', male: 'مرد', female: 'زنان',
  },
};

// Fallback to English for any missing key
function translate(lang, key) {
  return T[lang]?.[key] ?? T.English[key] ?? key;
}

// ── Country → Language mapping ──────────────────────────────────────────
const COUNTRY_LANG = {
  'IN': 'हिंदी',   // India default
  'PK': 'اردو',
  'BD': 'বাংলা',
  'NP': 'नेपाली',
  'CA': 'English', 'GB': 'English', 'US': 'English', 'AU': 'English', 'SG': 'English', 'LK': 'English',
  // Indian state codes (from geolocation)
  'KA': 'ಕನ್ನಡ',  'TN': 'தமிழ்',  'AP': 'తెలుగు', 'TG': 'తెలుగు',
  'KL': 'മലയാളം', 'MH': 'मराठी',  'GJ': 'ગુજરાતી', 'PB': 'ਪੰਜਾਬੀ',
  'WB': 'বাংলা',  'AS': 'অসমীয়া', 'OR': 'ଓଡ଼ିଆ',   'JK': 'कश्मीरी',
  'MN': 'মৈতৈলোন্', 'GA': 'कोंकणी',
};

// ── Enhanced location-based detection ─────────────────────────────────────
async function detectLanguage() {
  const saved = localStorage.getItem('sa_language');
  if (saved) return saved;

  try {
    // 1. GPS (most accurate)
    const pos = await new Promise((resolve, reject) => 
      navigator.geolocation.getCurrentPosition(resolve, reject, { 
        timeout: 8000, enableHighAccuracy: true 
      })
    );
    const { latitude, longitude } = pos.coords;
    
    // Reverse geocode
    const geoRes = await fetch(
      `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`
    );
    const geoData = await geoRes.json();
    const suggested = COUNTRY_LANG[geoData.countryCode] || COUNTRY_LANG['IN'];
    if (suggested && LANGUAGES.some(l => l.code === suggested)) {
      return suggested;
    }
  } catch (gpsErr) {
    // 2. IP geolocation fallback
    try {
      const ipRes = await fetch('https://ipapi.co/json/');
      const ipData = await ipRes.json();
      const suggested = COUNTRY_LANG[ipData.country_code] || 'English';
      if (LANGUAGES.some(l => l.code === suggested)) {
        return suggested;
      }
    } catch (ipErr) {
      console.log('Location detection failed, using browser fallback');
    }
  }

  // 3. Browser locale fallback (original logic)
  const browserLang = (navigator.language || 'en').split('-')[0].toLowerCase();
  for (const lang of LANGUAGES) {
    if (lang.locale.includes(browserLang)) return lang.code;
  }
  return 'English';
}

// ── Context ────────────────────────────────────────────────────────────────
const LanguageContext = createContext({
  language: 'English',
  setLanguage: () => {},
  t: (k) => k,
  navLinks: [],
  suggestedLanguage: null,
  dismissSuggestion: () => {},
});

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('English');
  const [suggestedLanguage, setSuggestedLanguageState] = useState(null);

  // Initialize language detection
  useEffect(() => {
    detectLanguage().then(setLanguageState).catch(() => {});
    if (localStorage.getItem('sa_language')) return; // already manually set
    const browserLang = (navigator.language || 'en').split('-')[0].toLowerCase();
    for (const lang of LANGUAGES) {
      if (lang.locale.includes(browserLang) && lang.code !== language) {
        setSuggestedLanguageState(lang.code);
        break;
      }
    }
  }, []);

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('sa_language', lang);
    setSuggestedLanguageState(null);
  };

  const dismissSuggestion = () => setSuggestedLanguageState(null);

  const t = (key) => translate(language, key);

  const navLinks = [
    [t('dashboard'),     '/parent/dashboard'],
    [t('myChild'),       '/parent/child-profile'],
    [t('vaccines'),      '/parent/vaccination'],
    [t('growth'),        '/parent/growth'],
    [t('dietPlan'),      '/parent/diet-plan'],
    [t('schemes'),       '/parent/schemes'],
    [t('reports'),       '/parent/reports'],
    [t('notifications'), '/parent/notifications'],
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, navLinks, suggestedLanguage, dismissSuggestion }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
